# Generated by Django 3.0.3 on 2020-11-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice1',
            name='img',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='practice1',
            name='pdf',
            field=models.FileField(upload_to='media'),
        ),
    ]
