# Generated by Django 3.0.3 on 2020-11-28 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20201128_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practice1',
            old_name='pdf',
            new_name='File',
        ),
        migrations.RenameField(
            model_name='practice1',
            old_name='chk1',
            new_name='check_if_image',
        ),
        migrations.RenameField(
            model_name='practice1',
            old_name='chk2',
            new_name='check_if_pdf',
        ),
        migrations.RemoveField(
            model_name='practice1',
            name='img',
        ),
    ]
