# Generated by Django 3.0.3 on 2020-11-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_practice2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=250)),
                ('File', models.FileField(upload_to='media')),
                ('check_if_image', models.BooleanField(default=False)),
                ('check_if_pdf', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GS1_Current',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=250)),
                ('File', models.FileField(upload_to='media')),
                ('check_if_image', models.BooleanField(default=False)),
                ('check_if_pdf', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GS1_static',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=250)),
                ('File', models.FileField(upload_to='media')),
                ('check_if_image', models.BooleanField(default=False)),
                ('check_if_pdf', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GS2_Current',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=250)),
                ('File', models.FileField(upload_to='media')),
                ('check_if_image', models.BooleanField(default=False)),
                ('check_if_pdf', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GS2_static',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=250)),
                ('File', models.FileField(upload_to='media')),
                ('check_if_image', models.BooleanField(default=False)),
                ('check_if_pdf', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GS3_Current',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=250)),
                ('File', models.FileField(upload_to='media')),
                ('check_if_image', models.BooleanField(default=False)),
                ('check_if_pdf', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GS3_static',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=250)),
                ('File', models.FileField(upload_to='media')),
                ('check_if_image', models.BooleanField(default=False)),
                ('check_if_pdf', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GS4_Current',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=250)),
                ('File', models.FileField(upload_to='media')),
                ('check_if_image', models.BooleanField(default=False)),
                ('check_if_pdf', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GS4_static',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=250)),
                ('File', models.FileField(upload_to='media')),
                ('check_if_image', models.BooleanField(default=False)),
                ('check_if_pdf', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sociology_current',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=250)),
                ('File', models.FileField(upload_to='media')),
                ('check_if_image', models.BooleanField(default=False)),
                ('check_if_pdf', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sociology_static',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=250)),
                ('File', models.FileField(upload_to='media')),
                ('check_if_image', models.BooleanField(default=False)),
                ('check_if_pdf', models.BooleanField(default=False)),
            ],
        ),
    ]
