# Generated by Django 3.0.3 on 2020-12-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_essay_gs1_current_gs1_static_gs2_current_gs2_static_gs3_current_gs3_static_gs4_current_gs4_static_so'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='topic_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='gs1_current',
            name='topic_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='gs1_static',
            name='topic_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='gs2_current',
            name='topic_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='gs2_static',
            name='topic_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='gs3_current',
            name='topic_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='gs3_static',
            name='topic_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='gs4_current',
            name='topic_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='gs4_static',
            name='topic_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='practice1',
            name='topic_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='practice2',
            name='topic_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='sociology_current',
            name='topic_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='sociology_static',
            name='topic_name',
            field=models.CharField(max_length=1000),
        ),
    ]
